### PR TITLE
Conda Build

### PR DESCRIPTION
**Pull request by xrl**
#3 

Introduces a feature flag for `dynamic-linking-from-conda` which changes `build.rs` to prefer dynamic linking and it invokes the `conda info --base` to find where packages exist.

@iwatobipen does this work for you?

In the project which depends on `rdkit-sys` you'll want to do something like:

```
[dependencies]
rdkit-sys = { git = "git@github.com:rdkit-rs/rdkit-sys.git", branch = "conda-build", features = ["dynamic-linking-from-conda"] }
```

also, you need to make sure that the conda packages are in your library path, on linux it'll be something like:

```
export LD_LIBRARY_PATH=$(conda info --base)/lib
```

before you can use the code. The Dockerfile.conda in this PR shows an example of how you can update your `/etc/ld.so.conf.d/conda` to include that conda path all the time (although the conda project does not recommend it).

### CODE REVIEW

**Comment by xrl** [comment]
I can't get the load path trickery to work in this environment just yet. But it works on my machine 😄

**Comment by xrl** [comment]
Specs are passing now, some wrangling of paths required to prefer system libraries but fall back to conda libraries. I'm not sure why the ldconfig isn't kicking in but at least I can workaround it for now.

**Comment by xrl** [comment]
I'm putting this thing to rest. I'm going to squash so I don't keep all these junk CI commits around.

**Comment by xrl** [comment]
@iwatobipen this has been tagged as rdkit-sys `0.2.12`. give it a whirl!

**Comment by iwatobipen** [comment]
Hi, I tried to new version of rdkit-sys and got error.
I think following part in build.rs is not compatible to conda env.

>        ("linux", _, _) => "/usr".to_string(),
conda include path is different from default path. So it'll cause error in build process.
Thanks,
@iwatobipen

**Comment by iwatobipen** [comment]
Hi, I confirmed that it worked with the option. Thanks!

**Pull request merged**
